// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLDkLqFeCeL0fb5W7eFmCG6CjEICr4WJg',
    appId: '1:676083946987:web:205abc1d5577dd63b6b5ae',
    messagingSenderId: '676083946987',
    projectId: 'dailycore-9e80a',
    authDomain: 'dailycore-9e80a.firebaseapp.com',
    storageBucket: 'dailycore-9e80a.firebasestorage.app',
    measurementId: 'G-MMEGDKB2WW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeX_LywF-ZVV3AiXpLXse8XqU5slPmCFs',
    appId: '1:676083946987:android:41a6487970a8e0e7b6b5ae',
    messagingSenderId: '676083946987',
    projectId: 'dailycore-9e80a',
    storageBucket: 'dailycore-9e80a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDxUVBFPfNildVhUNI30M8OcDpvVwwLb0',
    appId: '1:676083946987:ios:e89a60c20e9aa433b6b5ae',
    messagingSenderId: '676083946987',
    projectId: 'dailycore-9e80a',
    storageBucket: 'dailycore-9e80a.firebasestorage.app',
    iosBundleId: 'com.example.dailycore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDxUVBFPfNildVhUNI30M8OcDpvVwwLb0',
    appId: '1:676083946987:ios:e89a60c20e9aa433b6b5ae',
    messagingSenderId: '676083946987',
    projectId: 'dailycore-9e80a',
    storageBucket: 'dailycore-9e80a.firebasestorage.app',
    iosBundleId: 'com.example.dailycore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLDkLqFeCeL0fb5W7eFmCG6CjEICr4WJg',
    appId: '1:676083946987:web:4683d5536778aa26b6b5ae',
    messagingSenderId: '676083946987',
    projectId: 'dailycore-9e80a',
    authDomain: 'dailycore-9e80a.firebaseapp.com',
    storageBucket: 'dailycore-9e80a.firebasestorage.app',
    measurementId: 'G-GDSGKZ9K5Y',
  );
}
